blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls', namespace='post'))
]

blog/post/urls.py
from django.urls import path, include
from post import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>', views.post_detail, name='post_detail')
]

blog/post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'


    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    
    objects = models.Manager()
    published = PublishManager()


    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self) -> str:
        return self.title
    def get_absolute_url(self):
        return reverse("post:post_detail", kwargs={"id": self.id})
    

blog/post/views.py
from django.shortcuts import render, get_list_or_404
from django.http import Http404

from post.models import Post

def post_list(request):
    posts = Post.published.all()
    return render(request,
                  'post/list.html',
                  {'posts':posts}
    )

def post_detail(request, id):
    post = get_list_or_404(Post, id=id, status=Post.Status.PUBLISHED)
    """post = Post.published.get(id=id)"""
    return render(request,
                  'post/detail.html',
                  {'post': post}
    )

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
      <header>
          {% include 'includes/header.html' %}
      </header>
      <main>
        <div id="content">
          {% block content %}
            В блоке content отсутствуют данные.
          {% endblock %}
        </div>
      </main>
        <footer class="border-top text-center py-3">
          {% include 'includes/footer.html' %}
        </footer>
    </body>
</html>

blog/templates/includes/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}   
        
        {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}            
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endif %}     
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in post.comments.all %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        Автор коментария: 
        <a href="{% url 'posts:profile' comment.author.username %}">{{ comment.author.username }}</a>
      </h5>
      <div class="card my-4">
        <div class="card-header">
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    </div>
  </div>
{% endfor %} 

blog/templates/includes/footer.html
<p>© 2023 Copyright <span style="color:red">Si</span>otlas</p> 

blog/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'post:post_list' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Si</span>otlas
    </a>
  </div>
</nav> 

blog/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}

blog/templates/post/detail.html
{% extends 'base.html' %}
{% block content %}
{% for post in post %}
<div class="container">
    <!-- Начало глобального div.row с двумя колонками: 
     в левой колонке - имена авторов, в правой - блоки с текстом -->
    <div class="row">
  
      <!-- Начало левой колонки сайта со списком авторов -->
      <aside class="col-12 col-md-3">
        <ul class="list-group">
          <li class="list-group-item">Автор: {{ post.author }}</li>
          <li class="list-group-item">Заголовок: {{ post.title }}</li>
          <li class="list-group-item">Дата публикации: {{post.publish|date:"d E Y"}}</li>
        </ul>
      </aside>
      <!-- Конец левой колонки сайта -->
  
      <!-- Начало правой (широкой) колонки сайта -->
      <section class="col-12 col-md-9">
  
        <!-- Можно разбить на колонки содержимое любого блока.
         В этом div.row созданы четыре колонки с анонсами постов -->
        <div class="row">
  
       
  
        <div class="card-body">
            <h6 class="card-subtitle">
              <p class="date">
              Опубликовано {{ post.publish|date:"d E Y" }} автором {{ post.author }}.
              </p>
            </h6>
            <p>
              <h1>{{ post.title}}</h1>
            </p>
            <p>
              {{ post.body|linebreaksbr}}
            </p>
            </div>
        </div>
  
        
  
        
          <!-- Конец четвёртой колонки -->
        </div>  <!-- Конец вложенного div.row -->
      
  
      </section>  <!-- Конец правой (широкой) колонки сайта -->
    </div>  <!-- Конец div.row  -->
  </div>  <!-- Конец div.container -->
{% endfor %}
{% endblock content %}

blog/templates/post/list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

  <!-- Начало глобального div.row с двумя колонками: 
   в левой колонке - имена авторов, в правой - блоки с текстом -->
  <div class="row">

    <!-- Начало левой колонки сайта со списком авторов -->
    <aside class="col-12 col-md-3">
      <ul class="list-group">
        <li class="list-group-item">Аксентий Поприщин</li>
        <li class="list-group-item">Робинзон Крузо</li>
        <li class="list-group-item">Чарли Гордон</li>
        <li class="list-group-item">Владимир Высоцкий</li>
      </ul>
    </aside>
    <!-- Конец левой колонки сайта -->

    <!-- Начало правой (широкой) колонки сайта -->
    <section class="col-12 col-md-9">

      <!-- Можно разбить на колонки содержимое любого блока.
       В этом div.row созданы четыре колонки с анонсами постов -->
      <div class="row">

      {% for post in posts %}

      {% include 'post/post.html' %}

      {% endfor %}

      
        <!-- Конец четвёртой колонки -->
      </div>  <!-- Конец вложенного div.row -->
    

    </section>  <!-- Конец правой (широкой) колонки сайта -->
  </div>  <!-- Конец div.row  -->
</div>  <!-- Конец div.container -->
{% endblock content %}

blog/templates/post/post.html
<article class="col-12 col-md-9 col-xl-9">
    <div class="card">
      <h5 class="card-header">Автор: {{ post.author }}</h5>
      <h5 class="card-header">Заголовок: {{ post.title }}</h5>
      {% if post.group %}
      <h5><a href="{% url 'post:group_list' post.group.slug %}" class="list-group-item list-group-item-action">Группа:{{ post.group }}</a></h5>
      {% endif %}
      <div class="card-body">
        <h6 class="card-subtitle">
          <p class="date">
            Дата публикации:{{ post.publish|date:"d E Y" }}
          </p>
        </h6>
        <p>
          {{ post.body|truncatewords:30|linebreaksbr}}
        </p>
        <div class="d-grid gap-2 mx-auto">
          <a href="{{post.get_absolute_url}}" class="btn btn-secondary">Читать целиком</a>
        </div>
      </div>
    </div>
  </article>
  <p></p>